config/routes.rb
Rails.application.routes.draw do
  get "/tracking-info", to: "cookies#index"
  get "/cookie-consent", to: "cookies#consent"
  post "/cookie-consent", to: "cookies#consent"
  post "/reset-cookie-consent", to: "cookies#reset_consent"
  get "/about", to: "welcome#about"
  resource :session
  resources :passwords, param: :token
  resources :users, except: [ :index, :destroy ]
  resources :portfolios, except: []
  resources :portfolio_items, except: [ :index ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "welcome#index"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :portfolio_items, dependent: :destroy
  has_rich_text :description
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  include Pagy::Backend
  allow_unauthenticated_access only: %i[ show ]
  before_action :set_portfolio, only: %i[ show edit update ]

  def index
    @portfolios = Portfolio.all
    respond_to do |format|
      format.html
      format.json { render json: @portfolios }
    end
  end

  def new
    @user = Current.session.user
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    user = Current.session.user

    if user.portfolio
      respond_to do |format|
        format.html { redirect_to portfolio_path(user.portfolio), notice: "Portfolio creation failed, portfolio already exists" }
        format.json { render json: { 'error': "Portfolio already exists" }, status: :unprocessable_entity }
      end
    else
      @portfolio.user = user
      respond_to do |format|
        if @portfolio.save
          format.html { redirect_to portfolio_path(@portfolio), notice: "Portfolio was successfully created" }
          format.json { render :show, status: :created, location: @portfolio }
        else
          format.html { render :new, status: :unprocessable_entity  }
          format.json { render json: { 'error': "Could not create portfolio" }, status: :unprocessable_entity }
        end
      end
    end
  end

  def show
    if !@portfolio
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render json: { 'error': "Profile not found" }, status: :not_found }
      end
    else
      @pagy, @records = pagy(PortfolioItem.where(portfolio_id: @portfolio.id))
      respond_to do |format|
        format.html
        format.json { render json: @portfolio }
      end
    end
  end

  def edit
    if Current.session.user.id != @portfolio.user.id
      respond_to do |format|
        format.html { redirect_to portfolio_path(@portfolio), notice: "Cannot edit other user's profile." }
        format.json { render json: { 'error': "Access denied" }, status: :forbidden }
      end
    end
  end

  def update
    if Current.session.user.id != @portfolio.user.id
      respond_to do |format|
        format.html { redirect_to portfolio_path(@portfolio), notice: "Cannot edit other user's profile." }
        format.json { render json: { 'error': "Access denied" }, status: :forbidden }
      end
    end

    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolio_path(@portfolio), notice: "Portfolio settings successfully updated." }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_portfolio
      begin
        @portfolio = Portfolio.find(params.expect(:id))
      rescue
        @portfolio = nil
      end
    end

    def portfolio_params
      params.require(:portfolio).permit(
        :title,
        :introduction,
        :description
      )
    end
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, class: "contents") do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited portfolio data from being saved:</h2>

      <ul>
        <% portfolio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label class="form-control w-full max-w-xs mt-12">
    <div class="label">
      <span class="label-text">Portfolio title</span>
    </div>
    <div class="w-full sm:w-4/5">
      <%= form.text_field :title, required: true, autofocus: true, autocomplete: "title", placeholder: "Title for portfolio", value: portfolio.title || params[:title], class: "input input-bordered w-full max-w-xs" %>
    </div>
  </label>

  <label class="form-control w-full mt-6">
    <div class="label">
      <span class="label-text">Portfolio introduction (short introduction shown in portfolio listing)</span>
    </div>
    <div class="w-full">
      <%= form.text_area :introduction, required: true, autofocus: true, placeholder: "Short introduction for portfolio", value: portfolio.introduction || params[:introduction], class: "textarea textarea-bordered h-24 w-full" %>
    </div>
  </label>

  <div class="flex w-full flex-col">
    <div class="divider divider-default mt-12 md:mt-16"></div>
  </div>

  <label class="form-control w-full max-w-xs mt-6 mb-4">
    <div class="label">
      <span class="label-text">Full rich text description</span>
    </div>
  </label>
  <%= form.rich_text_area :description, class: "prose max-w-none" %>

  <div class="my-4 mt-8">
    <%= link_to "Add new portfolio item", new_portfolio_item_path(portfolio_id: @portfolio.id) %>
  </div>

  <div class="flex flex-col xs:flex-row mt-8 items-center gap-y-2 xs:gap-x-2 sm:w-4/5">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium cursor-pointer justify-self-center w-full" %>
    <%= link_to "Show portfolio", @portfolio, class: "link-button rounded-lg py-3 px-5 bg-gray-100 inline-block text-center font-medium w-full" %>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<div id="<%= dom_id portfolio %>" class="text-base-content">
  <h1 class="text-2xl xs:text-4xl lg:text-6xl font-semibold lg:font-medium text-base-content mb-6 mt-3 xs:mb-12 xs:mt-6 lg:mb-24 lg:mt-12">
    <%= @portfolio.title %>
  </h1>
  <div class="prose xl:prose-lg max-w-none">
    <%= @portfolio.description %>
  </div>
  <h2 id="portfolio-items" class="text-xl xs:text-2xl lg:text-4xl font-semibold lg:font-medium text-base-content mb-6 mt-6 xs:mb-12 xs:mt-12 lg:mb-20 lg:mt-24">
    Portfolio items
  </h2>
  <% if @pagy.pages > 1 %>
    <div class="mb-6 mt-4"><%== pagy_nav(@pagy, fragment: '#portfolio-items') %></div>
  <% end %>
  <div class="mb-6">
    <% @records.each do |portfolio_item| %>
      <%= render partial: 'portfolio_items/portfolio_item_list_item', locals: { portfolio_item: portfolio_item } %>
    <% end %>
  </div>
  <% if @pagy.pages > 1 %>
    <div class="mb-6"><%== pagy_nav(@pagy, fragment: '#portfolio-items') %></div>
  <% end %>
</div>

app/views/portfolios/edit.html.erb
<div class="mx-auto md:w-2/3 mt-12 w-full">
  <h1 class="font-bold text-4xl">Edit general portfolio data</h1>

  <%= render "form", portfolio: @portfolio %>
</div>

app/views/portfolios/index.html.erb
<h1>Public portfolio listing</h1>

app/views/portfolios/new.html.erb
<div class="flex flex-col items-center mx-auto sm:w-96 w-full">
  <h1 class="font-bold text-4xl">Create portfolio</h1>

  <%= render "form", portfolio: @portfolio %>
</div>

app/views/portfolios/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <% if !@portfolio %>
      <p>Portfolio not found</p>
    <% else %>
      <%= render @portfolio %>

      <% if authenticated? && Current.session.user.id == @portfolio.user.id %>
        <%= link_to "Edit portfolio", edit_portfolio_path(@portfolio), class: "link-button mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium text-center w-full xs:w-1/2" %>
      <% end %>
    <% end %>
  </div>
</div>