config/routes.rb
Rails.application.routes.draw do
  get "/tracking-info", to: "cookies#index"
  get "/cookie-consent", to: "cookies#consent"
  post "/cookie-consent", to: "cookies#consent"
  post "/reset-cookie-consent", to: "cookies#reset_consent"
  get "/about", to: "welcome#about"
  resource :session
  resources :passwords, param: :token
  resources :users, except: [ :index, :destroy ]
  resources :portfolios, except: []
  resources :portfolio_items, except: [ :index ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "welcome#index"
end

app/views/shared/_cookie_banner.html.erb
<%= turbo_frame_tag "cookie_consent_banner" do %>
  <% if session[:cookie_consent].nil? %>
    <section class="fixed bottom-0 left-0 right-0 p-4 bg-base-100 shadow-md pt-6 pb-6">
      <div class="w-full max-w-screen-xl xl:px-8 container mx-auto flex flex-col md:flex-row justify-between items-center">
        <div class="space-y-4 pr-0 md:pr-6">
          <h3>
            This site will always use a session cookie that provides basic functionality to the site.
            There are no advertising or tracking cookies.
          </h3>
          <p>
            You can reset your choice at any time on the tracking information page.
          </p>
          <%= link_to "Learn more", tracking_info_path, class: "mt-4", target: "_top" %>
        </div>
        <div class="flex flex-col md:flex-row items-center space-y-2 md:space-y-0 md:space-x-4">
          <%= button_to "Accept cookies", cookie_consent_path(cookies: true), class: "btn btn-primary mt-2 md:mt-0", method: :post %>
          <%= button_to "Reject cookies", cookie_consent_path(cookies: false), class: "btn mt-2 md:mt-0", method: :post %>
        </div>
      </div>
    </section>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center mt-auto bg-base-200 text-base-content rounded p-10 w-full max-w-screen-xl mx-auto">
  <nav class="grid grid-flow-col gap-4">
    <a href="/about" class="link link-hover">About</a>
    <a class="link link-hover">Contact</a>
    <a class="link link-hover">Jobs</a>
    <a href="/tracking-info" class="link link-hover">Tracking info</a>
  </nav>
  <nav>
    <div class="grid grid-flow-col gap-4">
      <a>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current">
          <path
            d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
        </svg>
      </a>
      <a>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current">
          <path
            d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
        </svg>
      </a>
      <a>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current">
          <path
            d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
        </svg>
      </a>
    </div>
  </nav>
  <aside>
    <p>Copyright © <%= Date.today.year %> - All rights reserved by Karl</p>
  </aside>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar bg-neutral text-neutral-content w-full max-w-screen-xl mx-auto">
  <div class="flex-1">
    <%= link_to "Portfolio manager", root_path, class: "btn btn-ghost text-xl max-xs:w-1/2" %>
  </div>
  <div class="flex-none">
    <div data-controller="theme">
      <label class="swap swap-rotate">
      <!-- this hidden checkbox controls the state -->
      <input type="checkbox" class="theme-controller" data-action="theme#change" value="dark" style="display:none" />
      <!-- sun icon -->
      <svg
        class="swap-off h-10 w-10 fill-current"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24">
        <path
          d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z" />
      </svg>
      <!-- moon icon -->
      <svg
        class="swap-on h-10 w-10 fill-current"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24">
        <path
          d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z" />
      </svg>
      </label>
    </div>
    <% if authenticated? %>
      <div class="dropdown dropdown-end text-accent-content">
        <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <% if Current.session.user.avatar.attached? %>
              <%= image_tag Current.session.user.avatar.variant(:thumb) %>
            <% else %>
              <img
                alt="Tailwind CSS Navbar component"
                src="https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp" />
            <% end %>
          </div>
        </div>
        <ul
          tabindex="0"
          class="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
          <li class="text-base-content">
            <%= link_to user_path(Current.try(:session).try(:user)), class: "justify-between" do %>
              User profile<span class="badge">New</span>
            <% end %>
          </li>
          <li class="text-base-content"><%= link_to "User settings", edit_user_path(Current.try(:session).try(:user)) %></li>
          <% if Current.session.user.portfolio %>
            <li class="text-base-content"><%= link_to "Portfolio", portfolio_path(Current.try(:session).try(:user).try(:portfolio)) %></li>
            <li class="text-base-content"><%= link_to "Portfolio settings", edit_portfolio_path(Current.try(:session).try(:user).try(:portfolio)) %></li>
          <% end %>
          <li class="text-base-content"><%= link_to "Logout", session_path, data: { "turbo-method": :delete } %></li>
        </ul>
      </div>
    <% else %>
      <div>
        <%= link_to "Login", new_session_path, class: "btn btn-ghost" %>
      </div>
    <% end %>
  </div>
</div>