config/routes.rb
Rails.application.routes.draw do
  get "/tracking-info", to: "cookies#index"
  get "/cookie-consent", to: "cookies#consent"
  post "/cookie-consent", to: "cookies#consent"
  post "/reset-cookie-consent", to: "cookies#reset_consent"
  get "/about", to: "welcome#about"
  resource :session
  resources :passwords, param: :token
  resources :users, except: [ :index, :destroy ]
  resources :portfolios, except: []
  resources :portfolio_items, except: [ :index ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "welcome#index"
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  allow_unauthenticated_access

  def index
  end

  def consent
    session[:cookie_consent] = params[:cookies] if params[:cookies].present?
  end

  def reset_consent
    session[:cookie_consent] = nil
    redirect_to cookie_consent_path
  end
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/views/cookies/consent.html.erb
<%= render 'shared/cookie_banner' %>

app/views/cookies/index.html.erb
<div class="prose">
  <h1>Cookie and tracking information</h1>
  <p>
    This site only uses a session cookie in order to provide basic functionality.
    No ad or tracking cookies are used.
    Declining cookies will not prevent the session cookie from being set as this would prevent the site
    from functioning correctly and among other things prevent
    <a href="https://owasp.org/www-community/attacks/csrf">
      CSRF protection
    </a>
    from functioning. This setting will, however, prevent any possible future ad or tracking cookies from being used.
    If you have previously declined cookies, you can accept them again by clicking the button below.
    You may also decline cookies if you have previously accepted them.
  </p>
  <%= button_to "Reset cookie consent", reset_cookie_consent_path, class: "btn btn-primary", data: { turbo_frame: "cookie_consent_banner" }, method: :post %>
</div>