config/routes.rb
Rails.application.routes.draw do
  get "/tracking-info", to: "cookies#index"
  get "/cookie-consent", to: "cookies#consent"
  post "/cookie-consent", to: "cookies#consent"
  post "/reset-cookie-consent", to: "cookies#reset_consent"
  get "/about", to: "welcome#about"
  resource :session
  resources :passwords, param: :token
  resources :users, except: [ :index, :destroy ]
  resources :portfolios, except: []
  resources :portfolio_items, except: [ :index ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "welcome#index"
end

app/models/portfolio_item.rb
# Define class PortfolioItem
class PortfolioItem < ApplicationRecord
  belongs_to :portfolio
  has_rich_text :description
  has_many_attached :images

  validates :title, presence: true
  validates :url, presence: true
  validates :repository_url, presence: true
  validates :images, content_type: [ "image/png", "image/jpg", "image/jpeg" ], limit: { max: 10 }, size: { less_than: 5.megabytes }
end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController
  allow_unauthenticated_access only: %i[ show ]
  before_action :set_portfolio_item, only: %i[ show edit update destroy ]

  def index
    @portfolio_items = PortfolioItem.all

    respond_to do |format|
      format.html
      format.json { render json: @portfolio_items }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @portfolio_item }
    end
  end

  def new
    @user = Current.session.user
    @portfolio = @user.portfolio
    @portfolio_item = PortfolioItem.new
  end

  def edit
    @portfolio = @portfolio_item.portfolio
    if Current.session.user.id != @portfolio_item.portfolio.user.id
      respond_to do |format|
        format.html { redirect_to portfolio_item_path(@portfolio_item), notice: "Cannot edit other user's profile." }
        format.json { render json: { 'error': "Access denied" }, status: :forbidden }
      end
    end
  end

  def create
    @user = Current.session.user
    @portfolio = @user.portfolio
    @portfolio_item = PortfolioItem.new(portfolio_item_params)
    @portfolio_item.portfolio = @portfolio

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to @portfolio_item, notice: "Portfolio item was successfully created." }
        format.json { render json: @portfolio_item, status: :created, location: @portfolio_item }
      else
        format.html { render action: "new", status: :unprocessable_entity }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if Current.session.user.id != @portfolio_item.portfolio.user.id
      respond_to do |format|
        format.html { redirect_to portfolio_item_path(@portfolio_item), notice: "Cannot edit other user's profile." }
        format.json { render json: { 'error': "Access denied" }, status: :forbidden }
      end
    end

    respond_to do |format|
      if @portfolio_item.update(portfolio_item_params)
        format.html { redirect_to @portfolio_item, notice: "Portfolio item was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit", status: :unprocessable_entity }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if Current.session.user.id != @portfolio_item.portfolio.user.id
      respond_to do |format|
        format.html { redirect_to portfolio_item_path(@portfolio_item), notice: "Cannot edit other user's profile." }
        format.json { render json: { 'error': "Access denied" }, status: :forbidden }
      end
    end

    @portfolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portfolio_items_url }
      format.json { head :no_content }
    end
  end

  private

  def set_portfolio_item
    @portfolio_item = PortfolioItem.find(params.expect(:id))
  end

  def portfolio_item_params
    params.require(:portfolio_item).permit(:title, :description, :url, :repository_url, images: [])
  end
end

app/views/portfolio_items/_form.html.erb
<%= form_with(model: portfolio_item, class: "contents") do |form| %>
  <% if portfolio_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(portfolio_item.errors.count, "error") %> prohibited portfolio item from being saved:</h2>

      <ul>
        <% portfolio_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label class="form-control w-full max-w-xs mt-12">
    <div class="label">
      <span class="label-text">Portfolio item title</span>
    </div>
    <div class="w-full sm:w-4/5">
      <%= form.text_field :title, required: true, autofocus: true, autocomplete: "title", placeholder: "Title for portfolio item", value: portfolio_item.title || params[:title], class: "input input-bordered w-full max-w-xs" %>
    </div>
  </label>

  <label class="form-control w-full max-w-md mt-8">
    <div class="label">
      <span class="label-text">Portfolio item url</span>
    </div>
    <div class="w-full sm:w-4/5">
      <%= form.text_field :url, required: true, autofocus: true, autocomplete: "url", placeholder: "URL for portfolio item", value: portfolio_item.url || params[:url], class: "input input-bordered w-full max-w-md" %>
    </div>
  </label>

  <label class="form-control w-full max-w-md mt-8">
    <div class="label">
      <span class="label-text">Portfolio item repository url</span>
    </div>
    <div class="w-full sm:w-4/5">
      <%= form.text_field :repository_url, required: true, autofocus: true, autocomplete: "repository_url", placeholder: "Repository URL for portfolio item", value: portfolio_item.repository_url || params[:repository_url], class: "input input-bordered w-full max-w-md" %>
    </div>
  </label>

  <div class="flex w-full flex-col">
    <div class="divider divider-default mt-12 md:mt-16"></div>
  </div>

  <label class="form-control w-full max-w-xs mt-6 mb-4">
    <div class="label">
      <span class="label-text text-lg">Full rich text description</span>
    </div>
  </label>
  <%= form.rich_text_area :description, class: "prose max-w-none" %>

  <% portfolio_item.images.each do |image| %>
    <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
  <% end %>

  <label class="form-control w-full max-w-md mt-8">
    <div class="label">
      <span class="label-text">Screenshots or other images</span>
    </div>
    <div class="w-full sm:w-4/5">
      <%= form.file_field :images, multiple: true, class: "file-input file-input-bordered file-input-primary w-full max-w-xs" %>
    </div>
  </label>

  <div class="flex flex-col md:flex-row mt-12 mb-12 items-center gap-y-2 xs:gap-x-2 sm:w-full">
    <%= form.submit class: "btn btn-primary justify-self-center w-full md:w-1/2" %>
    <%= link_to "Show portfolio", @portfolio, class: "link-button btn btn-secondary justify-self-center w-full md:w-1/2" %>
  </div>
<% end %>

app/views/portfolio_items/_portfolio_item.html.erb
<div id="<%= dom_id portfolio_item %>">
  <h1 class="text-2xl xs:text-4xl lg:text-6xl font-semibold lg:font-medium mb-6 mt-3 xs:mb-12 xs:mt-6 lg:mb-24 lg:mt-12">
    <%= @portfolio_item.title %>
  </h1>
  <div class="prose xl:prose-lg max-w-none">
    <%= @portfolio_item.description %>
  </div>

  <% if @portfolio_item.images.attached? %>
    <h2 class="text-xl xs:text-2xl lg:text-4xl font-semibold lg:font-medium mb-6 mt-6 xs:mb-12 xs:mt-12 lg:mb-20 lg:mt-24">
      Images
    </h2>
    <div class="carousel w-full">
      <% @portfolio_item.images.each_with_index do |image, index| %>
        <div id="slide<%= index + 1 %>" class="carousel-item relative w-full">
          <%= image_tag image.variant(resize_to_fit: [800, nil]), class: "w-full object-contain cursor-pointer", onclick: "openModal('#{rails_blob_url(image)}')" %>
          <div class="absolute left-2 md:left-4 right-2 md:right-4 top-1/2 flex -translate-y-1/2 transform justify-between">
            <a href="#slide<%= index.zero? ? @portfolio_item.images.length : index %>" class="btn btn-circle max-sm:btn-sm link-button" data-turbo="false">❮</a>
            <a href="#slide<%= index + 2 > @portfolio_item.images.length ? 1 : index + 2 %>" class="btn btn-circle max-sm:btn-sm link-button" data-turbo="false">❯</a>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <div id="imageModal" class="modal" onclick="closeModal()">
    <div class="modal-box w-full w-11/12 max-w-7xl mx-auto p-0 md:p-4 rounded-none md:rounded-md flex flex-col items-center">
      <img id="modalImage" src="" alt="Full Size" class="max-w-full h-auto" />
      <div class="modal-action w-full flex justify-end mt-4">
        <a href="#" class="btn btn-secondary link-button">Close</a>
      </div>
    </div>
  </div>

  <div class="prose xl:prose-lg max-w-none mt-12 md:mt-18">
    <% if @portfolio_item.url.present? || @portfolio_item.repository_url.present? %>
      <h2>Links</h2>
      <ul>
      <% if @portfolio_item.url.present? %>
        <li>Visit the site: <a href="<%= @portfolio_item.url %>" target="_blank">Visit site</a></li>
      <% end %>
      <% if @portfolio_item.repository_url.present? %>
        <li>Visit the repository: <a href="<%= @portfolio_item.repository_url %>" target="_blank">Visit repository</a></li>
      <% end %>
      </ul>
    <% end %>
  </div>
</div>

<script>
  function openModal(imageUrl) {
    const modal = document.getElementById('imageModal');
    const modalImage = document.getElementById('modalImage');

    modalImage.src = imageUrl;
    modal.classList.add('modal-open');
  }

  function closeModal() {
    const modal = document.getElementById('imageModal');
    modal.classList.remove('modal-open');
  }

  document.querySelector('.modal-action a').addEventListener('click', function(event) {
    event.preventDefault();
    closeModal();
  });
</script>

app/views/portfolio_items/_portfolio_item_list_item.html.erb
<div class="card card-normal bg-base-100 hover:bg-base-200 w-full border-t-2 first:border-t-0 rounded-none" id="<%= dom_id portfolio_item %>">
  <div class="card-body !pl-0 !pr-0">
    <h2 class="card-title text-base-content"><%= portfolio_item.title %></h2>
    <p class="text-base-content"><%= portfolio_item.description %></p>
    <div class="card-actions justify-end">
      <%= button_tag "Check this out", class: "btn btn-primary", onclick: "window.location.href='#{portfolio_item_path(portfolio_item)}'" %>
    </div>
  </div>
</div>

app/views/portfolio_items/edit.html.erb
<div class="mx-auto md:w-2/3 mt-12 w-full">
  <h1 class="font-bold text-4xl">Edit portfolio item</h1>

  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolio_items/new.html.erb
<div class="mx-auto md:w-2/3 mt-12 w-full">
  <h1 class="font-bold text-4xl">Create portfolio item</h1>

  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolio_items/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <% if !@portfolio_item %>
      <p>Portfolio item not found</p>
    <% else %>
      <%= render @portfolio_item %>

    <div class="flex flex-col xs:flex-row mt-8 items-center gap-y-2 xs:gap-x-2 sm:w-4/5">
      <% if authenticated? && Current.session.user.id == @portfolio_item.portfolio.user.id %>
          <%= link_to "Edit portfolio item", edit_portfolio_item_path(@portfolio_item), class: "btn btn-primary link-button w-full xs:w-1/2" %>
        <% end %>
        <%= link_to "Back to portfolio", portfolio_path(@portfolio_item.portfolio, anchor: "portfolio-items"), class: "btn btn-secondary link-button w-full xs:w-1/2" %>
      </div>
    <% end %>
  </div>
</div>